# Generated by Django 5.1.1 on 2024-10-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAgricultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('humedad', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('viento', models.FloatField()),
                ('precipitacion', models.FloatField()),
                ('ph_suelo', models.FloatField()),
                ('nitrogeno', models.FloatField()),
                ('fertilizacion', models.FloatField()),
                ('densidad', models.FloatField()),
                ('n_flores', models.IntegerField()),
                ('plagas', models.IntegerField()),
                ('caida_frutos', models.FloatField()),
                ('rendimiento', models.FloatField()),
            ],
        ),
    ]
