# Generated by Django 5.1.1 on 2024-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='caida_frutos',
            new_name='Caida_Frutos',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='fertilizacion',
            new_name='Fertilizacion',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='humedad',
            new_name='Humedad',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='n_flores',
            new_name='N_Flores',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='nitrogeno',
            new_name='Nitrogeno',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='plagas',
            new_name='Plagas',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='precipitacion',
            new_name='Precipitacion',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='ph_suelo',
            new_name='pH_Suelo',
        ),
    ]
