# Generated by Django 5.1.1 on 2024-10-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_rename_caida_frutos_datosagricultura_caida_frutos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='densidad',
            new_name='Densidad',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='radiacion_solar',
            new_name='Radiacion_solar',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='rendimiento',
            new_name='Rendimiento',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='temp_max',
            new_name='Temp_Max',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='temp_min',
            new_name='Temp_Min',
        ),
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='viento',
            new_name='Viento',
        ),
    ]
