# Generated by Django 5.1.1 on 2024-10-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_rename_densidad_datosagricultura_densidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosagricultura',
            old_name='Radiacion_solar',
            new_name='Radiacion_Solar',
        ),
    ]
