# Generated by Django 5.1.2 on 2024-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_datosagricultura_created_datosagricultura_pkuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosagricultura',
            name='nhectaria',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datosagricultura',
            name='tiempo_pro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
